name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: aws
      url: https://your-production-site.com  # Optional

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Deploy Frontend
        run: bash scripts/deploy/deploy_frontend.sh prod

      - name: Deploy Backend
        run: bash scripts/deploy/deploy_backend.sh prod
